name: Generate Pages

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 * * * *"

jobs:
  lqty-supply:
    name: Generate API files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
        env:
          # Workaround for https://github.com/actions/setup-node/issues/317
          FORCE_COLOR: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch API data
        run: yarn once
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          TRANSPOSE_API_KEY: ${{ secrets.TRANSPOSE_API_KEY }}

      - name: Commit generated files
        uses: EndBug/add-and-commit@v7.2.1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          message: "chore: update generated files"
          default_author: github_actions
          add: docs
          pull_strategy: NO-PULL
          push: --force origin HEAD:pages
